name: flutteer_todo_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"
  adaptive_icon_backgrounnd: "#ffffff"
  adaptive_icon_foregroud: "assets/background.png"

assets:
  - assets/
